APP = psq_reader
SRC = psq_reader

LIB =

CFLAGS   = $(FAST_CFLAGS)
CXXFLAGS = $(FAST_CXXFLAGS)
LDFLAGS  = $(FAST_LDFLAGS)

CPPFLAGS = -DNCBI_MODULE=BLASTDB $(ORIG_CPPFLAGS)
LIBS = $(ORIG_LIBS)

REQUIRES = objects
